services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - tailwind
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=localhost 127.0.0.1
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./django_project:/app
      - static_volume:/app/staticfiles
      - tailwind_output:/app/static/css
  
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
  
  tailwind:
    image: node:18-slim
    working_dir: /app
    restart: always
    volumes:
      - ./package.json:/app/package.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./django_project:/app/django_project
    command: >
      bash -c "npm install &&
               npm run dev"

volumes:
  postgres_data:
  static_volume:
  tailwind_output: 